### ISSUE TITLE
你好，有个问题请教，可以给视频添加滤镜然后到处视频地址吗

### ISSUE THREAD

**Issue by niehuaming** [microshow/FastFFmpegAndroid#1]
你好，有个问题请教，可以给视频添加滤镜然后到处视频地址吗，
就是我本地的MP4文件，然后简单的一个视频滤镜效果，比如黑白什么的，然后到处滤镜过后的视频吗？

**Comment by microshow** [comment]
支持的， 比如黑白滤镜命令:  ffmpeg -y -i /storage/emulated/0/1/input.mp4 -vf lutyuv=u=128:v=128 -preset superfast /storage/emulated/0/1/result.mp4
